const employees = [
  {
    id: 1,
    firstname: "Ali",
    email: "employee1@example.com",
    password: "123",
    taskSummary: { active: 1, newTask: 1, completed: 1, failed: 1 },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Design Homepage",
        description: "Create the UI for the homepage using Tailwind.",
        date: "2025-08-20",
        category: "work",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Fix Navbar Bug",
        description: "Resolve alignment issue in the navbar.",
        date: "2025-08-15",
        category: "urgent",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Submit Report",
        description: "Submit last week's project report to the manager.",
        date: "2025-08-10",
        category: "work",
      },
    ],
  },
  {
    id: 2,
    firstname: "Sara",
    email: "employee2@example.com",
    password: "123",
    taskSummary: { active: 1, newTask: 1, completed: 1, failed: 1 },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Prepare Presentation",
        description: "Make a PPT for client meeting.",
        date: "2025-08-22",
        category: "work",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Buy Office Supplies",
        description: "Order new markers and sticky notes.",
        date: "2025-08-12",
        category: "personal",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Update Website Banner",
        description: "Change the summer sale banner to autumn theme.",
        date: "2025-08-05",
        category: "urgent",
      },
    ],
  },
  {
    id: 3,
    firstname: "Ahmed",
    email: "employee3@example.com",
    password: "123",
    taskSummary: { active: 1, newTask: 1, completed: 1, failed: 1 },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Code Review",
        description: "Review the merge requests from frontend team.",
        date: "2025-08-21",
        category: "work",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Fix API Endpoint",
        description: "Correct the response format of /users endpoint.",
        date: "2025-08-11",
        category: "urgent",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Weekly Standup",
        description: "Join the weekly standup meeting with manager.",
        date: "2025-08-06",
        category: "work",
      },
    ],
  },
  {
    id: 4,
    firstname: "Fatima",
    email: "employee4@example.com",
    password: "123",
    taskSummary: { active: 1, newTask: 0, completed: 1, failed: 2 },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Database Backup",
        description: "Backup the production database to cloud storage.",
        date: "2025-08-23",
        category: "urgent",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Client Feedback",
        description: "Document feedback from client meeting.",
        date: "2025-08-13",
        category: "work",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Fix Login Issue",
        description: "Resolve issue where login fails for some users.",
        date: "2025-08-08",
        category: "urgent",
      },
    ],
  },
  {
    id: 5,
    firstname: "Usman",
    email: "employee5@example.com",
    password: "123",
    taskSummary: { active: 1, newTask: 1, completed: 1, failed: 1 },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Content Writing",
        description: "Write blog post for company website.",
        date: "2025-08-19",
        category: "work",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Team Lunch",
        description: "Organize team lunch for Friday.",
        date: "2025-08-14",
        category: "personal",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Prepare Invoice",
        description: "Generate invoice for July billing cycle.",
        date: "2025-08-09",
        category: "work",
      },
    ],
  },
];

  const admin = [
    {
      id: 1,
      firstname: "admin",
      email: "admin@example.com",
      password: "123",
    },
  ];

  export const setLocalStorage = ()=>{
    localStorage.setItem('employees',JSON.stringify(employees))
    localStorage.setItem('admin',JSON.stringify(admin))
}
export const getLocalStorage = ()=>{
    const employees = JSON.parse(localStorage.getItem('employees'))
    const admin = JSON.parse(localStorage.getItem('admin'))

    return {employees,admin}
}